# Generated by Django 5.1.3 on 2025-03-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Faq Category Model',
                'verbose_name_plural': 'Faq Category Models',
                'db_table': 'faqcategory',
            },
        ),
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='name')),
                ('question_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('answer', models.CharField(max_length=255, verbose_name='answer')),
                ('answer_uz', models.CharField(max_length=255, null=True, verbose_name='answer')),
                ('answer_ru', models.CharField(max_length=255, null=True, verbose_name='answer')),
                ('answer_en', models.CharField(max_length=255, null=True, verbose_name='answer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='api.faqcategorymodel')),
            ],
            options={
                'verbose_name': 'FaqModel',
                'verbose_name_plural': 'FaqModels',
                'db_table': 'faq',
            },
        ),
    ]
