# Generated by Django 5.1.3 on 2025-03-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'CategoryModel',
                'verbose_name_plural': 'CategoryModels',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'TagModel',
                'verbose_name_plural': 'TagModels',
                'db_table': 'tag',
            },
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question',
            field=models.CharField(max_length=255, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('content_uz', models.TextField(null=True, verbose_name='content')),
                ('content_ru', models.TextField(null=True, verbose_name='content')),
                ('content_en', models.TextField(null=True, verbose_name='content')),
                ('image', models.ImageField(upload_to='post/', verbose_name='image')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('categories', models.ManyToManyField(to='api.categorymodel', verbose_name='categories')),
                ('tags', models.ManyToManyField(to='api.tagmodel', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'PostModel',
                'verbose_name_plural': 'PostModels',
                'db_table': 'post',
            },
        ),
    ]
