# Generated by Django 5.1.3 on 2025-03-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_educationmodel_experiencemodel_projectmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Stack CategoryModel',
                'verbose_name_plural': 'Stack CategoryModels',
                'db_table': 'stackcategory',
            },
        ),
        migrations.CreateModel(
            name='StackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='api.stackcategorymodel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'StackModel',
                'verbose_name_plural': 'StackModels',
                'db_table': 'stack',
            },
        ),
        migrations.DeleteModel(
            name='SkilModel',
        ),
    ]
