# Generated by Django 5.1.3 on 2025-03-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactmodel'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='images',
            field=models.ManyToManyField(to='shared.mediamodel', verbose_name='images'),
        ),
    ]
