# Generated by Django 5.1.3 on 2025-03-07 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_projectmodel_image_projectmodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencemodel',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='comments'), blank=True, null=True, size=None, verbose_name='comments'),
        ),
    ]
