# Generated by Django 5.1.3 on 2025-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_experiencemodel_comments'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencemodel',
            name='images',
            field=models.ManyToManyField(to='shared.mediamodel', verbose_name='images'),
        ),
    ]
