# Generated by Django 5.1.3 on 2025-03-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_experiencemodel_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['position'], 'verbose_name': 'ProjectModel', 'verbose_name_plural': 'ProjectModels'},
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
