# Generated by Django 5.1.3 on 2025-03-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_projectmodel_options_projectmodel_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmodel',
            options={'ordering': ['position'], 'verbose_name': 'EducationModel', 'verbose_name_plural': 'EducationModels'},
        ),
        migrations.AlterModelOptions(
            name='experiencemodel',
            options={'ordering': ['position'], 'verbose_name': 'ExperienceModel', 'verbose_name_plural': 'ExperienceModels'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['position'], 'verbose_name': 'PostModel', 'verbose_name_plural': 'PostModels'},
        ),
        migrations.AlterModelOptions(
            name='stackcategorymodel',
            options={'ordering': ['position'], 'verbose_name': 'Stack CategoryModel', 'verbose_name_plural': 'Stack CategoryModels'},
        ),
        migrations.AlterModelOptions(
            name='stackmodel',
            options={'ordering': ['position'], 'verbose_name': 'StackModel', 'verbose_name_plural': 'StackModels'},
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stackcategorymodel',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stackmodel',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
