# Generated by Django 5.1.3 on 2025-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_educationmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='desc',
            field=models.TextField(default=1, verbose_name='desc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.categorymodel', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tagmodel', verbose_name='tags'),
        ),
    ]
